name = "agc-news-bot"
main = "main.js"
compatibility_date = "2024-03-20"

# Atur jadwal otomatis bot berjalan (Setiap 3 jam sekali)
[triggers]
crons = ["0 */3 * * *"]

# Hubungkan ke Cloudflare D1 Database
[[d1_databases]]
binding = "DB"
database_name = "agc-database"
database_id = "3146a626-35d1-427c-93ad-13d86d9a8287"
